version: '3'

services:
  php:
    build:
      context: ./docker/php

    environment:
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        start_with_request=trigger
        client_host=host.docker.internal
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=symfonyApp
    ports:
      - '9000:9000'
    volumes:
      - ./:/srv/app

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/srv/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php